In [1]:
test1A = 'ALOHA'
test1B = 'HALLOA'

In [35]:
import string
import random
import time
import numpy as np

In [4]:
def longest_common_subsequence(L1,L2):
    if len(L1) == 0 or len(L2) == 0:
        return 0
    if L1[0] == L2[0]:
        return 1 + longest_common_subsequence(L1[1:],L2[1:])
    else:
        return max(longest_common_subsequence(L1[1:],L2),longest_common_subsequence(L1,L2[1:]))

In [5]:
longest_common_subsequence(test1A,test1B)

4

In [25]:
def test():
    return longest_common_subsequence(''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(10)),''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(10)))

In [28]:
start = time.time()
lengthSum = 0
for i in range(1000):
    lengthSum += test()
    
end = time.time()
print('Average length:' + str(lengthSum/1000))
print('Average Time:' + str((end-start)/100))

Average length:1.677
Average Time:1.3956380605697631


In [57]:
def longest_common_subsequence_memoization(L1,L2):
    L = np.zeros((len(L1),len(L2)))
    

In [58]:
longest_common_subsequence_memoization(test1A,test1B)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
